[workspace]
authors = ["Evan Foster <evanfost@andrew.cmu.edu>"]
channels = ["robostack-humble", "conda-forge"]
name = "LEAP-sprayer"
platforms = ["osx-arm64", { name = "jetson-orin-nano", platform = "linux-aarch64", cuda = "12.6" }, "linux-64"]
version = "0.1.0"

[activation]
scripts = ["install/setup.sh"]

[tasks]
build = {cmd = "colcon build --symlink-install", inputs = ["src"], outputs = ["build", "install"]}

[tasks.pkg-create]
args = ["package", "name"]
cmd = "ros2 pkg create --build-type ament_python --destination-directory src --node-name {{ name }} {{ package }}"

[dependencies]
python = "~=3.11.0"
ros-humble-desktop = ">=0.10.0,<0.11"
colcon-common-extensions = ">=0.3.0,<0.4"
setuptools = "<=58.2.0"
ros-humble-vision-opencv = ">=3.2.1,<4"
opencv = ">=4.11.0,<5"
ros-humble-rqt-image-view = ">=1.2.0,<2"
