[workspace]
authors = ["Evan Foster <evanfost@andrew.cmu.edu>"]
channels = ["robostack-humble", "conda-forge"]
name = "LEAP-sprayer"
platforms = ["osx-arm64", { name = "jetson-orin-nano", platform = "linux-aarch64", cuda = "12.6" }, "linux-64"]
version = "0.1.0"

[tasks]

[dependencies]
python = "~=3.11.0"
ros-humble-desktop = ">=0.10.0,<0.11"
colcon-common-extensions = ">=0.3.0,<0.4"
setuptools = "<=58.2.0"
