[workspace]
authors = ["Evan Foster <evanfost@andrew.cmu.edu>"]
channels = [
  "robostack-humble", "conda-forge",
  "https://prefix.dev/robostack-humble-realsense-camera-osx" # allows for pulling realsense libraries on macos
]
name = "LEAP-sprayer"
platforms = [{ name = "jetson-orin-nano", platform = "linux-aarch64", cuda = "12.6" }, "linux-64", "osx-arm64"]
version = "0.1.0"

[feature.source_ros2]
activation = { scripts = ["install/setup.sh"] }

# used for arduino development and deployment
[feature.firmware.dependencies]
platformio = "~=6.1.19"

[environments]
sourced = ["source_ros2"]
# disable default imports (we don't need ros2 in this)
firmware = { features = ["firmware"], no-default-feature = true }

[tasks.build]
cmd = "colcon build --symlink-install"
inputs = ["src"]
outputs = ["build", "install"]

[tasks.launch]
cmd = """
{% if not pixi.is_linux %}\
echo \"WARNING: not all features work on non-Linux platforms\" && \
{% endif %}\
ros2 launch bringup launch.py
"""
depends-on = [{task = "build"}]
default-environment = "sourced"

[tasks.pkg-create]
args = ["package", "name"]
cmd = "ros2 pkg create --build-type ament_python --destination-directory src --node-name {{ name }} {{ package }}"

[dependencies]
python = "~=3.11.0"
ros-humble-desktop = ">=0.10.0,<0.11"
colcon-common-extensions = ">=0.3.0,<0.4"
setuptools = "<=58.2.0"
ros-humble-vision-opencv = ">=3.2.1,<4"
opencv = ">=4.11.0,<5"
ros-humble-rqt-image-view = ">=1.2.0,<2"
ros-humble-realsense2-camera = ">=4.55.1,<5"
ros-humble-foxglove-bridge = ">=0.8.5,<0.9"
ros-humble-vision-msgs = ">=4.1.1,<5"
ros-humble-foxglove-msgs = ">=2.3.0,<3"
ros-humble-message-filters = ">=4.3.7,<5"
pyserial = ">=3.5,<4"
