[env]
platform = atmelavr
board = uno
framework = arduino

[env:live]
lib_deps =
    adafruit/Adafruit MCP23017 Arduino Library @ ~2.3.2
build_src_filter =
    +<*>
    -<main_*.cpp>
    +<main_live.cpp>

[env:test_led]
build_src_filter =
    +<*>
    -<main_*.cpp>
    +<main_test_led.cpp>
