[env]
framework = arduino

[board:uno]
platform = atmelavr
board = uno

[board:nano]
platform = atmelmegaavr
board = nano_every

; when adding a new platform, do three things
; 1. declare [board:my_board]
;   a. platform
;   b. board
; 2. add corresponding envs for it for all targets
;   a. [env:my_board_some_target]
;      extends = board:my_board, target:some_target
; 3. update pixi.toml feature.firmware.tasks.build-firmware task
;    to accept your new board as a choice for "board"

[target:live]
lib_deps =
    adafruit/Adafruit MCP23017 Arduino Library @ ~2.3.2
build_src_filter =
    +<*>
    -<main_*.cpp>
    +<main_live.cpp>

[target:live_pwm]
lib_deps =
    adafruit/Adafruit MCP23017 Arduino Library @ ~2.3.2
build_src_filter =
    +<*>
    -<main_*.cpp>
    +<main_live_pwm.cpp>

[target:test_led]
build_src_filter =
    +<*>
    -<main_*.cpp>
    +<main_test_led.cpp>

; when adding a new target, do two things
; 1. declare [target:my_target]
;   a. filter for it's correct main.cpp
;   b. declare dependencies
; 2. add corresponding envs for it
;   a. [env:uno_my_target]
;      extends = board:uno, target:my_target
;   b. [env:nano_my_target]
;      extends = board:nano, target:my_target

[env:uno_live]
extends = board:uno, target:live

[env:nano_live]
extends = board:nano, target:live

[env:uno_live_pwm]
extends = board:uno, target:live_pwm

[env:nano_live_pwm]
extends = board:nano, target:live_pwm

[env:uno_test_led]
extends = board:uno, target:test_led

[env:nano_test_led]
extends = board:nano, target:test_led
