[env]
framework = arduino

[board:uno]
platform = atmelavr
board = uno

[board:nano]
platform = atmelmegaavr
board = nano_every

[env:uno_live]
extends = board:uno
lib_deps =
    adafruit/Adafruit MCP23017 Arduino Library @ ~2.3.2
build_src_filter =
    +<*>
    -<main_*.cpp>
    +<main_live.cpp>

[env:nano_live]
extends = board:nano
lib_deps =
    adafruit/Adafruit MCP23017 Arduino Library @ ~2.3.2
build_src_filter =
    +<*>
    -<main_*.cpp>
    +<main_live.cpp>

[env:uno_test_led]
extends = board:uno
build_src_filter =
    +<*>
    -<main_*.cpp>
    +<main_test_led.cpp>

[env:nano_test_led]
extends = board:nano
build_src_filter =
    +<*>
    -<main_*.cpp>
    +<main_test_led.cpp>
